site_name: Dnamw's blog

theme:
  name: material
  custom_dir: overrides

  features:
    - content.code.select
    - content.code.copy
    - content.code.cop
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.path
  
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default       
      primary: blue       
      accent: deep purple   
      toggle:
          icon: material/brightness-7
          name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      primary: black
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search

  - blog:
      archive: false
      # archive_date_format: MMMM yyyy
      post_readtime: true
      post_url_format: "{categories}/{slug}"
      post_url_max_categories: 2

  - document-dates:
      position: top
      type: date
      # exclude:
      date_format: '%Y-%m-%d'
      time_format: '%H:%M:%S'
      show_author: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

repo_name: dnamw/blog
repo_url: https://github.com/dnamw/blog

nav:
  - Home:
    - intro: index.md
  - Programming Tips:
    - intro: programming_tips/index.md
    - C String and String_Views: programming_tips/c_string.md
    - Quine: programming_tips/quine.md
  - Tiny Projects:
    - intro: tiny_projects/index.md
    - Lambda for C: tiny_projects/lambda_for_c.md